apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 36
    buildToolsVersion '35.0.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "shmutalov.verusminer9000"
        minSdkVersion 23
        targetSdkVersion 36 // Now using native library directory for binaries (jniLibs) - compatible with Android 10+ W^X policy
        versionCode 10
        versionName "0.0.17"
        buildConfigField "long", "BUILD_TIME", System.currentTimeMillis() + "L"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }


    buildTypes {
        release {
            minifyEnabled false // Disable it for now, problem while fetching Json data for Pool API
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'shmutalov.verusminer9000'
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'org.ocpsoft.prettytime:prettytime:5.0.7.Final'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0'
}
